[0m15:32:39.038709 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103eb69e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db6a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db70d0>]}


============================== 15:32:39.041588 | 239de5aa-12bd-4e3f-9e82-8d727a1e56d6 ==============================
[0m15:32:39.041588 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:32:39.041933 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/luis.herrera/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_water', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:32:39.051011 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/Users/luis.herrera/.dbt')}
[0m15:32:39.051345 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:32:39.052870 [debug] [MainThread]: Starter project path: /Users/luis.herrera/.local/share/virtualenvs/waterProject-dataland-_LoBuj3S/lib/python3.10/site-packages/dbt/include/starter_project
[0m15:32:39.057624 [info ] [MainThread]: 
Your new dbt project "dbt_water" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:32:39.057916 [info ] [MainThread]: Setting up your profile.
[0m15:33:47.994585 [info ] [MainThread]: Profile dbt_water written to /Users/luis.herrera/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:33:47.997402 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 69.00162, "process_in_blocks": "0", "process_kernel_time": 0.097696, "process_mem_max_rss": "97632256", "process_out_blocks": "0", "process_user_time": 0.64216}
[0m15:33:47.997796 [debug] [MainThread]: Command `dbt init` succeeded at 15:33:47.997702 after 69.00 seconds
[0m15:33:47.998243 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103eb69e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104eb5c30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d173a0>]}
[0m15:33:47.998587 [debug] [MainThread]: Flushing usage events
[0m15:33:48.323622 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:11:19.479393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10722e9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10812ab60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10812b220>]}


============================== 16:11:19.482116 | bf2341d5-a7f2-4019-941e-ae49019fd639 ==============================
[0m16:11:19.482116 [info ] [MainThread]: Running with dbt=1.9.3
[0m16:11:19.482437 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/luis.herrera/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -s my_first_dbt_model', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:11:19.482768 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/luis.herrera/Desktop/code/data-engineering/projects/waterProject-dataland/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:11:19.483868 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.040494584, "process_in_blocks": "0", "process_kernel_time": 0.074953, "process_mem_max_rss": "96878592", "process_out_blocks": "0", "process_user_time": 0.609008}
[0m16:11:19.484121 [debug] [MainThread]: Command `dbt run` failed at 16:11:19.484071 after 0.04 seconds
[0m16:11:19.484332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10722e9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10808e230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10812b310>]}
[0m16:11:19.484527 [debug] [MainThread]: Flushing usage events
[0m16:11:19.808522 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:14:35.243072 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d269e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c1ec20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c1f2e0>]}


============================== 16:14:35.245581 | 5292db04-8682-4e92-91c9-7930ec3358f5 ==============================
[0m16:14:35.245581 [info ] [MainThread]: Running with dbt=1.9.3
[0m16:14:35.245943 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/luis.herrera/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:14:35.246292 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/luis.herrera/Desktop/code/data-engineering/projects/waterProject-dataland/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:14:35.247430 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.041383583, "process_in_blocks": "0", "process_kernel_time": 0.073761, "process_mem_max_rss": "97992704", "process_out_blocks": "0", "process_user_time": 0.590699}
[0m16:14:35.247740 [debug] [MainThread]: Command `dbt run` failed at 16:14:35.247682 after 0.04 seconds
[0m16:14:35.247963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d269e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086aea40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c1f340>]}
[0m16:14:35.248186 [debug] [MainThread]: Flushing usage events
[0m16:14:35.561813 [debug] [MainThread]: An error was encountered while trying to flush usage events
